spring:
  application:
    name: loan-service

server:
  port: 8081
  
management:
  endpoint:
    health:
      show-details: always
    
  endpoints:
      web:
        exposure:
          include: health
  health:
    circuitbreakers:
      enabled: true
      
      
resilience4j:
  circuitbreaker:
    instances:
      loan-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 90s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        
        
              
      
      
              
                 